_wandb:
    value:
        cli_version: 0.19.0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "2":
                - 1
                - 41
                - 49
                - 51
                - 55
                - 63
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.0
            "8":
                - 5
            "12": 0.19.0
            "13": linux-x86_64
accum_iter:
    value: 1
batch_size:
    value: 8
blr:
    value: 0.0001
clip_grad:
    value: 5
layer_decay:
    value: 0.75
lr:
    value: 3.125e-06
min_lr:
    value: 1e-06
model_name:
    value: part_ae_d8_m8_l32
warmup_epochs:
    value: 1
weight_decay:
    value: 0.05
